### ISSUE TITLE
A WRONG parameter in "package.json"

### ISSUE THREAD

**Issue by RaebingZhong** [xmindltd/xmindmark#2]
The index.d.ts path parameter(types) in package.json lost a middle document address.
It should be 
`"types": "./dist/src/index.d.ts",`
but not 
` "types": "./dist/index.d.ts",`.
Otherwise, there is always a warning that the d.ts file can't be found when using this repo as a module in typescript.

**Comment by parrotdance** [comment]
Hi, thanks for your feedback.

We have reproduced and fixed this problem at version `0.3.1`. Please update and try it out again.

This issue will be closed and feel free to re-open it if problem still exist.
